services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - nlp-service
    networks:
      - app-network

  nlp-service:
    build:
      context: ./server/nlp-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge