import React from 'react';
import { FaRegNewspaper, FaPencilAlt, FaRegListAlt } from 'react-icons/fa';
import { useNavigate } from 'react-router-dom';

// Please note that some of the Homepage text was generated with the assistance of GPT-4

function HomePage() {
  let navigate = useNavigate();

  return (
    <div className="p-8">
      <h1 className="font-proximanova font-bold text-4xl mb-4">Welcome to AttentiveMind: Empowering Focus & Learning</h1>
      <p className="font-manrope font-light text-2xl">
        AttentiveMind is a study tool designed for students with ADHD or those who experience short attention spans. 
        By integrating cutting-edge NLP and LLMs, AttentiveMind enhances learning and retention with features tailored for academic success.
      </p>

      <ul className="list-disc pl-5 text-lg mt-6 mb-6">
        <li><strong>Text Summarization:</strong> Quickly condense lecture transcripts and readings into manageable summaries.</li>
        <li><strong>Key Concept Extraction:</strong> Identify and extract crucial concepts to highlight essential information.</li>
        <li><strong>Advanced Note-Taking:</strong> Utilize tools like highlighting, text sharpening/blurring, and customizable colors to improve focus.</li>
        <li><strong>Flashcard Generation:</strong> Convert summaries and notes into flashcards to enhance review sessions.</li>
      </ul>
      
      <p className="font-manrope font-light text-lg mb-4">
        Join us in redefining study habits and transform how you interact with educational content, tailored to overcome the challenges of short attention spans. Select an option below to get started!
      </p>

      <div className="flex justify-around items-center mt-10">
        {/* Text Summarization & Key Concept Extraction Button */}
        <div className="text-center m-2">
          <button onClick={() => navigate('/text-summarization')} className="flex flex-col items-center justify-center p-4 bg-primary hover:bg-primary-700 text-white font-bold py-2 px-4 rounded">
            <FaRegNewspaper className="text-4xl mb-2" />
            <span>Text Summarization & Key Concept Extraction</span>
          </button>
        </div>

        {/* Note-Taking Button */}
        <div className="text-center m-2">
          <button onClick={() => navigate('/note-taking')} className="flex flex-col items-center justify-center p-4 bg-secondary hover:bg-secondary-700 text-white font-bold py-2 px-4 rounded">
            <FaPencilAlt className="text-4xl mb-2" />
            <span>Note-Taking</span>
          </button>
        </div>

        {/* Flashcard Generation Button */}
        <div className="text-center m-2">
          <button onClick={() => navigate('/flashcard-generation')} className="flex flex-col items-center justify-center p-4 bg-accent hover:bg-accent-700 text-white font-bold py-2 px-4 rounded">
            <FaRegListAlt className="text-4xl mb-2" />
            <span>Flashcard Generation</span>
          </button>
        </div>
      </div>
      <p className="text-sm italic text-gray-600 mt-4">
        <strong>Disclaimer:</strong> The content generated by our AI tools, while advanced, may not always be entirely accurate. These language models can produce results that, though convincing, may not be based on factual data. We recommend always reviewing and verifying the accuracy of the generated content to ensure its reliability before use.
      </p>
    </div>
  )
};

export default HomePage;